import { getGlobalData } from '@/data/loaders';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/app/theme-provider';
import '@/assets/styles/globals.css';
import SideNavigation from '@/components/organisms/SideNavigation/SideNavigation';
import Header from '@/components/organisms/Header/Header';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter', display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalData();
  console.dir(globalData, { depth: null });

  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      {/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body
        className={`${inter.variable} font-inter antialiased bg-white text-slate-800 dark:bg-slate-900 dark:text-slate-200 tracking-tight`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="max-w-7xl mx-auto">
            <div className="min-h-screen flex">
              <SideNavigation
                menuItems={globalData.sideNavigation.menuItem}
                logo={globalData.sideNavigation.logo}
              />

              {/* Main content */}
              <main className="grow overflow-hidden px-6">
                <div className="w-full h-full max-w-[1072px] mx-auto flex flex-col">
                  <Header
                    name={globalData.header.link.name}
                    href={globalData.header.link.href}
                  />

                  {children}
                </div>
              </main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
